# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vtk_selections_test_ui.ui'
#
# Created: Thu May 14 18:57:43 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(436, 569)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btn_switch_view = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_switch_view.sizePolicy().hasHeightForWidth())
        self.btn_switch_view.setSizePolicy(sizePolicy)
        self.btn_switch_view.setObjectName(_fromUtf8("btn_switch_view"))
        self.gridLayout_2.addWidget(self.btn_switch_view, 0, 0, 1, 1)
        self.btn_show_hide = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_show_hide.sizePolicy().hasHeightForWidth())
        self.btn_show_hide.setSizePolicy(sizePolicy)
        self.btn_show_hide.setObjectName(_fromUtf8("btn_show_hide"))
        self.gridLayout_2.addWidget(self.btn_show_hide, 0, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chk_replace = QtGui.QCheckBox(self.dockWidgetContents)
        self.chk_replace.setObjectName(_fromUtf8("chk_replace"))
        self.verticalLayout.addWidget(self.chk_replace)
        self.chk_append = QtGui.QCheckBox(self.dockWidgetContents)
        self.chk_append.setObjectName(_fromUtf8("chk_append"))
        self.verticalLayout.addWidget(self.chk_append)
        self.chk_remove = QtGui.QCheckBox(self.dockWidgetContents)
        self.chk_remove.setObjectName(_fromUtf8("chk_remove"))
        self.verticalLayout.addWidget(self.chk_remove)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.chk_any = QtGui.QCheckBox(self.dockWidgetContents)
        self.chk_any.setObjectName(_fromUtf8("chk_any"))
        self.verticalLayout_2.addWidget(self.chk_any)
        self.chk_nodes = QtGui.QCheckBox(self.dockWidgetContents)
        self.chk_nodes.setObjectName(_fromUtf8("chk_nodes"))
        self.verticalLayout_2.addWidget(self.chk_nodes)
        self.chk_elements = QtGui.QCheckBox(self.dockWidgetContents)
        self.chk_elements.setObjectName(_fromUtf8("chk_elements"))
        self.verticalLayout_2.addWidget(self.chk_elements)
        self.chk_points = QtGui.QCheckBox(self.dockWidgetContents)
        self.chk_points.setObjectName(_fromUtf8("chk_points"))
        self.verticalLayout_2.addWidget(self.chk_points)
        self.chk_bars = QtGui.QCheckBox(self.dockWidgetContents)
        self.chk_bars.setObjectName(_fromUtf8("chk_bars"))
        self.verticalLayout_2.addWidget(self.chk_bars)
        self.chk_tris = QtGui.QCheckBox(self.dockWidgetContents)
        self.chk_tris.setObjectName(_fromUtf8("chk_tris"))
        self.verticalLayout_2.addWidget(self.chk_tris)
        self.chk_quads = QtGui.QCheckBox(self.dockWidgetContents)
        self.chk_quads.setObjectName(_fromUtf8("chk_quads"))
        self.verticalLayout_2.addWidget(self.chk_quads)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.lnedt_selection = QtGui.QLineEdit(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedt_selection.sizePolicy().hasHeightForWidth())
        self.lnedt_selection.setSizePolicy(sizePolicy)
        self.lnedt_selection.setMinimumSize(QtCore.QSize(261, 20))
        self.lnedt_selection.setObjectName(_fromUtf8("lnedt_selection"))
        self.verticalLayout_3.addWidget(self.lnedt_selection)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(82, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cbx_left_click = QtGui.QComboBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbx_left_click.sizePolicy().hasHeightForWidth())
        self.cbx_left_click.setSizePolicy(sizePolicy)
        self.cbx_left_click.setMinimumSize(QtCore.QSize(82, 20))
        self.cbx_left_click.setObjectName(_fromUtf8("cbx_left_click"))
        self.cbx_left_click.addItem(_fromUtf8(""))
        self.cbx_left_click.addItem(_fromUtf8(""))
        self.cbx_left_click.addItem(_fromUtf8(""))
        self.cbx_left_click.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbx_left_click, 0, 1, 1, 1)
        self.cbx_right_click = QtGui.QComboBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbx_right_click.sizePolicy().hasHeightForWidth())
        self.cbx_right_click.setSizePolicy(sizePolicy)
        self.cbx_right_click.setMinimumSize(QtCore.QSize(82, 20))
        self.cbx_right_click.setObjectName(_fromUtf8("cbx_right_click"))
        self.cbx_right_click.addItem(_fromUtf8(""))
        self.cbx_right_click.addItem(_fromUtf8(""))
        self.cbx_right_click.addItem(_fromUtf8(""))
        self.cbx_right_click.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbx_right_click, 2, 1, 1, 1)
        self.cbx_ctrl_left_click = QtGui.QComboBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbx_ctrl_left_click.sizePolicy().hasHeightForWidth())
        self.cbx_ctrl_left_click.setSizePolicy(sizePolicy)
        self.cbx_ctrl_left_click.setMinimumSize(QtCore.QSize(82, 20))
        self.cbx_ctrl_left_click.setObjectName(_fromUtf8("cbx_ctrl_left_click"))
        self.cbx_ctrl_left_click.addItem(_fromUtf8(""))
        self.cbx_ctrl_left_click.addItem(_fromUtf8(""))
        self.cbx_ctrl_left_click.addItem(_fromUtf8(""))
        self.cbx_ctrl_left_click.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbx_ctrl_left_click, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(82, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.cbx_middle_click = QtGui.QComboBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbx_middle_click.sizePolicy().hasHeightForWidth())
        self.cbx_middle_click.setSizePolicy(sizePolicy)
        self.cbx_middle_click.setMinimumSize(QtCore.QSize(82, 20))
        self.cbx_middle_click.setObjectName(_fromUtf8("cbx_middle_click"))
        self.cbx_middle_click.addItem(_fromUtf8(""))
        self.cbx_middle_click.addItem(_fromUtf8(""))
        self.cbx_middle_click.addItem(_fromUtf8(""))
        self.cbx_middle_click.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbx_middle_click, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(82, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(82, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.frame = QtGui.QFrame(self.dockWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(0, 100))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.btn_fit_view = QtGui.QPushButton(self.frame)
        self.btn_fit_view.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.btn_fit_view.setObjectName(_fromUtf8("btn_fit_view"))
        self.btn_rotation_center = QtGui.QPushButton(self.frame)
        self.btn_rotation_center.setGeometry(QtCore.QRect(140, 20, 75, 23))
        self.btn_rotation_center.setObjectName(_fromUtf8("btn_rotation_center"))
        self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 1)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget", None))
        self.btn_switch_view.setText(_translate("DockWidget", "Switch View", None))
        self.btn_show_hide.setText(_translate("DockWidget", "Show/Hide", None))
        self.chk_replace.setText(_translate("DockWidget", "Replace", None))
        self.chk_append.setText(_translate("DockWidget", "Append", None))
        self.chk_remove.setText(_translate("DockWidget", "Remove", None))
        self.chk_any.setText(_translate("DockWidget", "Any", None))
        self.chk_nodes.setText(_translate("DockWidget", "Nodes", None))
        self.chk_elements.setText(_translate("DockWidget", "Elements", None))
        self.chk_points.setText(_translate("DockWidget", "Points", None))
        self.chk_bars.setText(_translate("DockWidget", "Bars", None))
        self.chk_tris.setText(_translate("DockWidget", "Tris", None))
        self.chk_quads.setText(_translate("DockWidget", "Quads", None))
        self.label.setText(_translate("DockWidget", "Left-Click", None))
        self.cbx_left_click.setItemText(0, _translate("DockWidget", "Rotate", None))
        self.cbx_left_click.setItemText(1, _translate("DockWidget", "Pan", None))
        self.cbx_left_click.setItemText(2, _translate("DockWidget", "Zoom", None))
        self.cbx_left_click.setItemText(3, _translate("DockWidget", "Select", None))
        self.cbx_right_click.setItemText(0, _translate("DockWidget", "Rotate", None))
        self.cbx_right_click.setItemText(1, _translate("DockWidget", "Pan", None))
        self.cbx_right_click.setItemText(2, _translate("DockWidget", "Zoom", None))
        self.cbx_right_click.setItemText(3, _translate("DockWidget", "Select", None))
        self.cbx_ctrl_left_click.setItemText(0, _translate("DockWidget", "Rotate", None))
        self.cbx_ctrl_left_click.setItemText(1, _translate("DockWidget", "Pan", None))
        self.cbx_ctrl_left_click.setItemText(2, _translate("DockWidget", "Zoom", None))
        self.cbx_ctrl_left_click.setItemText(3, _translate("DockWidget", "Select", None))
        self.label_4.setText(_translate("DockWidget", "Ctrl-Left-Click", None))
        self.cbx_middle_click.setItemText(0, _translate("DockWidget", "Rotate", None))
        self.cbx_middle_click.setItemText(1, _translate("DockWidget", "Pan", None))
        self.cbx_middle_click.setItemText(2, _translate("DockWidget", "Zoom", None))
        self.cbx_middle_click.setItemText(3, _translate("DockWidget", "Select", None))
        self.label_3.setText(_translate("DockWidget", "Right-Click", None))
        self.label_2.setText(_translate("DockWidget", "Middle-Click", None))
        self.btn_fit_view.setText(_translate("DockWidget", "Fit View", None))
        self.btn_rotation_center.setText(_translate("DockWidget", "Rot. Center", None))

