# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\CODE\10_PROJECT\FEMAnalysisTool\fem_post\view\view.ui'
#
# Created: Sat Mar 28 06:40:59 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(859, 647)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/qrc/074.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tab_model = QtGui.QTabWidget(self.centralwidget)
        self.tab_model.setDocumentMode(True)
        self.tab_model.setObjectName(_fromUtf8("tab_model"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitter_2 = QtGui.QSplitter(self.tab_1)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setAcceptDrops(True)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.vl = QtGui.QVBoxLayout()
        self.vl.setObjectName(_fromUtf8("vl"))
        self.gridLayout_2.addLayout(self.vl, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.tab_model.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tab_model.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.tab_model, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 859, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu_Group = QtGui.QMenu(self.menubar)
        self.menu_Group.setObjectName(_fromUtf8("menu_Group"))
        self.menu_Tools = QtGui.QMenu(self.menubar)
        self.menu_Tools.setObjectName(_fromUtf8("menu_Tools"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        self.menu_Toolbars = QtGui.QMenu(self.menu_View)
        self.menu_Toolbars.setObjectName(_fromUtf8("menu_Toolbars"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.tbar_grp = QtGui.QToolBar(MainWindow)
        self.tbar_grp.setObjectName(_fromUtf8("tbar_grp"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.tbar_grp)
        self.tbar_1 = QtGui.QToolBar(MainWindow)
        self.tbar_1.setMovable(True)
        self.tbar_1.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.tbar_1.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbar_1.setFloatable(True)
        self.tbar_1.setObjectName(_fromUtf8("tbar_1"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.tbar_1)
        self.tbar_showhide = QtGui.QToolBar(MainWindow)
        self.tbar_showhide.setObjectName(_fromUtf8("tbar_showhide"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.tbar_showhide)
        self.action_A1 = QtGui.QAction(MainWindow)
        self.action_A1.setCheckable(True)
        self.action_A1.setIcon(icon)
        self.action_A1.setObjectName(_fromUtf8("action_A1"))
        self.action_A2 = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/qrc/002.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_A2.setIcon(icon1)
        self.action_A2.setObjectName(_fromUtf8("action_A2"))
        self.action_A3 = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/qrc/097.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_A3.setIcon(icon2)
        self.action_A3.setObjectName(_fromUtf8("action_A3"))
        self.action_GRP1 = QtGui.QAction(MainWindow)
        self.action_GRP1.setObjectName(_fromUtf8("action_GRP1"))
        self.action_GRP2 = QtGui.QAction(MainWindow)
        self.action_GRP2.setObjectName(_fromUtf8("action_GRP2"))
        self.action_GRP3 = QtGui.QAction(MainWindow)
        self.action_GRP3.setObjectName(_fromUtf8("action_GRP3"))
        self.action_Open = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/qrc/folder32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon3)
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.action_View = QtGui.QAction(MainWindow)
        self.action_View.setCheckable(True)
        self.action_View.setObjectName(_fromUtf8("action_View"))
        self.action_Picking = QtGui.QAction(MainWindow)
        self.action_Picking.setObjectName(_fromUtf8("action_Picking"))
        self.action_Quit = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/qrc/exit-256.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Quit.setIcon(icon4)
        self.action_Quit.setObjectName(_fromUtf8("action_Quit"))
        self.action_nodevis = QtGui.QAction(MainWindow)
        self.action_nodevis.setCheckable(True)
        self.action_nodevis.setObjectName(_fromUtf8("action_nodevis"))
        self.action_elementvis = QtGui.QAction(MainWindow)
        self.action_elementvis.setCheckable(True)
        self.action_elementvis.setObjectName(_fromUtf8("action_elementvis"))
        self.action_Preferences = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/qrc/user_man_settings_setting_options_gear-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Preferences.setIcon(icon5)
        self.action_Preferences.setObjectName(_fromUtf8("action_Preferences"))
        self.action_Plugin_Manager = QtGui.QAction(MainWindow)
        self.action_Plugin_Manager.setObjectName(_fromUtf8("action_Plugin_Manager"))
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addAction(self.action_Preferences)
        self.menuFile.addAction(self.action_Quit)
        self.menu_Tools.addAction(self.action_Plugin_Manager)
        self.menu_Toolbars.addAction(self.action_View)
        self.menu_Toolbars.addAction(self.action_Picking)
        self.menu_View.addAction(self.menu_Toolbars.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Group.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.tbar_grp.addAction(self.action_GRP1)
        self.tbar_grp.addAction(self.action_GRP2)
        self.tbar_grp.addAction(self.action_GRP3)
        self.tbar_1.addAction(self.action_A1)
        self.tbar_1.addAction(self.action_A2)
        self.tbar_1.addAction(self.action_A3)
        self.tbar_showhide.addAction(self.action_nodevis)
        self.tbar_showhide.addAction(self.action_elementvis)

        self.retranslateUi(MainWindow)
        self.tab_model.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tab_model.setTabText(self.tab_model.indexOf(self.tab_1), _translate("MainWindow", "Model 1", None))
        self.tab_model.setTabText(self.tab_model.indexOf(self.tab_2), _translate("MainWindow", "Model 2", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menu_Group.setTitle(_translate("MainWindow", "&Group", None))
        self.menu_Tools.setTitle(_translate("MainWindow", "&Tools", None))
        self.menu_View.setTitle(_translate("MainWindow", "&View", None))
        self.menu_Toolbars.setTitle(_translate("MainWindow", "&Toolbars", None))
        self.tbar_grp.setWindowTitle(_translate("MainWindow", "Grouping Toolbar", None))
        self.tbar_grp.setToolTip(_translate("MainWindow", "Group Toolbar", None))
        self.tbar_grp.setStatusTip(_translate("MainWindow", "Group Tools", None))
        self.tbar_1.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.tbar_showhide.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.action_A1.setText(_translate("MainWindow", "&A1", None))
        self.action_A2.setText(_translate("MainWindow", "&A2", None))
        self.action_A3.setText(_translate("MainWindow", "&A3", None))
        self.action_GRP1.setText(_translate("MainWindow", "&GRP1", None))
        self.action_GRP2.setText(_translate("MainWindow", "GRP2", None))
        self.action_GRP3.setText(_translate("MainWindow", "GRP3", None))
        self.action_Open.setText(_translate("MainWindow", "&Open...", None))
        self.action_View.setText(_translate("MainWindow", "&View", None))
        self.action_Picking.setText(_translate("MainWindow", "&Picking", None))
        self.action_Quit.setText(_translate("MainWindow", "&Quit", None))
        self.action_Quit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_nodevis.setText(_translate("MainWindow", "NodeVis", None))
        self.action_elementvis.setText(_translate("MainWindow", "ElementVis", None))
        self.action_Preferences.setText(_translate("MainWindow", "&Preferences", None))
        self.action_Plugin_Manager.setText(_translate("MainWindow", "Plugin Manager", None))

import viewqrc_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

