# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\CODE\10_PROJECT\FEMAnalysisTool\fem_post\view\view.ui'
#
# Created: Wed Mar 18 05:51:29 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1052, 854)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        #self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.frame = QtGui.QFrame(self.splitter)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        #self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.vl = QtGui.QVBoxLayout()
        self.vl.setObjectName(_fromUtf8("vl"))
        self.gridLayout_2.addLayout(self.vl, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.splitter_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1052, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu_Group = QtGui.QMenu(self.menubar)
        self.menu_Group.setObjectName(_fromUtf8("menu_Group"))
        self.menu_Tools = QtGui.QMenu(self.menubar)
        self.menu_Tools.setObjectName(_fromUtf8("menu_Tools"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dock_msg = QtGui.QDockWidget(MainWindow)
        self.dock_msg.setObjectName(_fromUtf8("dock_msg"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.txt_msg = QtGui.QPlainTextEdit(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_msg.sizePolicy().hasHeightForWidth())
        self.txt_msg.setSizePolicy(sizePolicy)
        self.txt_msg.setMinimumSize(QtCore.QSize(0, 120))
        self.txt_msg.setMaximumSize(QtCore.QSize(16777215, 120))
        self.txt_msg.setObjectName(_fromUtf8("txt_msg"))
        self.gridLayout_3.addWidget(self.txt_msg, 0, 0, 1, 1)
        self.dock_msg.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dock_msg)
        self.tbar_grp = QtGui.QToolBar(MainWindow)
        self.tbar_grp.setObjectName(_fromUtf8("tbar_grp"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.tbar_grp)
        self.tbar_1 = QtGui.QToolBar(MainWindow)
        self.tbar_1.setMovable(True)
        self.tbar_1.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.tbar_1.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbar_1.setFloatable(True)
        self.tbar_1.setObjectName(_fromUtf8("tbar_1"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.tbar_1)
        self.dock_view1 = QtGui.QDockWidget(MainWindow)
        self.dock_view1.setObjectName(_fromUtf8("dock_view1"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.btn_switch = QtGui.QPushButton(self.dockWidgetContents_2)
        self.btn_switch.setObjectName(_fromUtf8("btn_switch"))
        self.gridLayout_5.addWidget(self.btn_switch, 4, 0, 1, 1)
        self.btn_bgcolor2 = QtGui.QPushButton(self.dockWidgetContents_2)
        self.btn_bgcolor2.setObjectName(_fromUtf8("btn_bgcolor2"))
        self.gridLayout_5.addWidget(self.btn_bgcolor2, 1, 0, 1, 1)
        self.btn_edgecolor = QtGui.QPushButton(self.dockWidgetContents_2)
        self.btn_edgecolor.setObjectName(_fromUtf8("btn_edgecolor"))
        self.gridLayout_5.addWidget(self.btn_edgecolor, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 9, 0, 1, 1)
        self.btn_perspectivetoggle = QtGui.QPushButton(self.dockWidgetContents_2)
        self.btn_perspectivetoggle.setObjectName(_fromUtf8("btn_perspectivetoggle"))
        self.gridLayout_5.addWidget(self.btn_perspectivetoggle, 5, 0, 1, 1)
        self.btn_bgcolor1 = QtGui.QPushButton(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_bgcolor1.sizePolicy().hasHeightForWidth())
        self.btn_bgcolor1.setSizePolicy(sizePolicy)
        self.btn_bgcolor1.setObjectName(_fromUtf8("btn_bgcolor1"))
        self.gridLayout_5.addWidget(self.btn_bgcolor1, 0, 0, 1, 1)
        self.btn_nofillededge = QtGui.QPushButton(self.dockWidgetContents_2)
        self.btn_nofillededge.setObjectName(_fromUtf8("btn_nofillededge"))
        self.gridLayout_5.addWidget(self.btn_nofillededge, 3, 0, 1, 1)
        self.btn_elementcolor = QtGui.QPushButton(self.dockWidgetContents_2)
        self.btn_elementcolor.setObjectName(_fromUtf8("btn_elementcolor"))
        self.gridLayout_5.addWidget(self.btn_elementcolor, 6, 0, 1, 1)
        self.btn_togglewire = QtGui.QPushButton(self.dockWidgetContents_2)
        self.btn_togglewire.setObjectName(_fromUtf8("btn_togglewire"))
        self.gridLayout_5.addWidget(self.btn_togglewire, 7, 0, 1, 1)
        self.btn_saveimg = QtGui.QPushButton(self.dockWidgetContents_2)
        self.btn_saveimg.setObjectName(_fromUtf8("btn_saveimg"))
        self.gridLayout_5.addWidget(self.btn_saveimg, 8, 0, 1, 1)
        self.dock_view1.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dock_view1)
        self.dock_picking = QtGui.QDockWidget(MainWindow)
        self.dock_picking.setObjectName(_fromUtf8("dock_picking"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.box_pick_button = QtGui.QPushButton(self.dockWidgetContents_3)
        self.box_pick_button.setAutoDefault(True)
        self.box_pick_button.setObjectName(_fromUtf8("box_pick_button"))
        self.gridLayout.addWidget(self.box_pick_button, 2, 0, 1, 1)
        self.points_button = QtGui.QPushButton(self.dockWidgetContents_3)
        self.points_button.setAutoDefault(True)
        self.points_button.setDefault(False)
        self.points_button.setFlat(False)
        self.points_button.setObjectName(_fromUtf8("points_button"))
        self.gridLayout.addWidget(self.points_button, 4, 1, 1, 1)
        self.bars_button = QtGui.QPushButton(self.dockWidgetContents_3)
        self.bars_button.setAutoDefault(True)
        self.bars_button.setDefault(False)
        self.bars_button.setFlat(False)
        self.bars_button.setObjectName(_fromUtf8("bars_button"))
        self.gridLayout.addWidget(self.bars_button, 5, 1, 1, 1)
        self.single_pick_button = QtGui.QPushButton(self.dockWidgetContents_3)
        self.single_pick_button.setAutoDefault(True)
        self.single_pick_button.setObjectName(_fromUtf8("single_pick_button"))
        self.gridLayout.addWidget(self.single_pick_button, 1, 0, 1, 1)
        self.toggle_hidden_button = QtGui.QPushButton(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggle_hidden_button.sizePolicy().hasHeightForWidth())
        self.toggle_hidden_button.setSizePolicy(sizePolicy)
        self.toggle_hidden_button.setObjectName(_fromUtf8("toggle_hidden_button"))
        self.gridLayout.addWidget(self.toggle_hidden_button, 9, 0, 1, 1)
        self.remove_selection_button = QtGui.QPushButton(self.dockWidgetContents_3)
        self.remove_selection_button.setAutoDefault(True)
        self.remove_selection_button.setDefault(False)
        self.remove_selection_button.setFlat(False)
        self.remove_selection_button.setObjectName(_fromUtf8("remove_selection_button"))
        self.gridLayout.addWidget(self.remove_selection_button, 7, 0, 1, 1)
        self.tris_button = QtGui.QPushButton(self.dockWidgetContents_3)
        self.tris_button.setAutoDefault(True)
        self.tris_button.setDefault(False)
        self.tris_button.setFlat(False)
        self.tris_button.setObjectName(_fromUtf8("tris_button"))
        self.gridLayout.addWidget(self.tris_button, 6, 1, 1, 1)
        self.any_button = QtGui.QPushButton(self.dockWidgetContents_3)
        self.any_button.setAutoDefault(True)
        self.any_button.setObjectName(_fromUtf8("any_button"))
        self.gridLayout.addWidget(self.any_button, 1, 1, 1, 1)
        self.nodes_button = QtGui.QPushButton(self.dockWidgetContents_3)
        self.nodes_button.setAutoDefault(True)
        self.nodes_button.setObjectName(_fromUtf8("nodes_button"))
        self.gridLayout.addWidget(self.nodes_button, 2, 1, 1, 1)
        self.selection_box = QtGui.QLineEdit(self.dockWidgetContents_3)
        self.selection_box.setObjectName(_fromUtf8("selection_box"))
        self.gridLayout.addWidget(self.selection_box, 8, 0, 1, 2)
        self.replace_selection_button = QtGui.QPushButton(self.dockWidgetContents_3)
        self.replace_selection_button.setAutoDefault(True)
        self.replace_selection_button.setObjectName(_fromUtf8("replace_selection_button"))
        self.gridLayout.addWidget(self.replace_selection_button, 5, 0, 1, 1)
        self.append_selection_button = QtGui.QPushButton(self.dockWidgetContents_3)
        self.append_selection_button.setAutoDefault(True)
        self.append_selection_button.setObjectName(_fromUtf8("append_selection_button"))
        self.gridLayout.addWidget(self.append_selection_button, 6, 0, 1, 1)
        self.elements_button = QtGui.QPushButton(self.dockWidgetContents_3)
        self.elements_button.setAutoDefault(True)
        self.elements_button.setDefault(False)
        self.elements_button.setFlat(False)
        self.elements_button.setObjectName(_fromUtf8("elements_button"))
        self.gridLayout.addWidget(self.elements_button, 3, 1, 1, 1)
        self.poly_pick_button = QtGui.QPushButton(self.dockWidgetContents_3)
        self.poly_pick_button.setAutoDefault(True)
        self.poly_pick_button.setDefault(False)
        self.poly_pick_button.setFlat(False)
        self.poly_pick_button.setObjectName(_fromUtf8("poly_pick_button"))
        self.gridLayout.addWidget(self.poly_pick_button, 3, 0, 1, 1)
        self.quads_button = QtGui.QPushButton(self.dockWidgetContents_3)
        self.quads_button.setAutoDefault(True)
        self.quads_button.setDefault(False)
        self.quads_button.setFlat(False)
        self.quads_button.setObjectName(_fromUtf8("quads_button"))
        self.gridLayout.addWidget(self.quads_button, 7, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.dockWidgetContents_3)
        self.label.setMinimumSize(QtCore.QSize(71, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.left_click_combo = QtGui.QComboBox(self.dockWidgetContents_3)
        self.left_click_combo.setMinimumSize(QtCore.QSize(69, 22))
        self.left_click_combo.setObjectName(_fromUtf8("left_click_combo"))
        self.left_click_combo.addItem(_fromUtf8(""))
        self.left_click_combo.addItem(_fromUtf8(""))
        self.left_click_combo.addItem(_fromUtf8(""))
        self.left_click_combo.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.left_click_combo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_2.setMinimumSize(QtCore.QSize(71, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.middle_click_combo = QtGui.QComboBox(self.dockWidgetContents_3)
        self.middle_click_combo.setMinimumSize(QtCore.QSize(69, 22))
        self.middle_click_combo.setObjectName(_fromUtf8("middle_click_combo"))
        self.middle_click_combo.addItem(_fromUtf8(""))
        self.middle_click_combo.addItem(_fromUtf8(""))
        self.middle_click_combo.addItem(_fromUtf8(""))
        self.middle_click_combo.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.middle_click_combo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_3.setMinimumSize(QtCore.QSize(71, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.right_click_combo = QtGui.QComboBox(self.dockWidgetContents_3)
        self.right_click_combo.setMinimumSize(QtCore.QSize(69, 22))
        self.right_click_combo.setObjectName(_fromUtf8("right_click_combo"))
        self.right_click_combo.addItem(_fromUtf8(""))
        self.right_click_combo.addItem(_fromUtf8(""))
        self.right_click_combo.addItem(_fromUtf8(""))
        self.right_click_combo.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.right_click_combo)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.dockWidgetContents_3)
        self.label_4.setMinimumSize(QtCore.QSize(71, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.ctrl_left_click_combo = QtGui.QComboBox(self.dockWidgetContents_3)
        self.ctrl_left_click_combo.setMinimumSize(QtCore.QSize(69, 22))
        self.ctrl_left_click_combo.setObjectName(_fromUtf8("ctrl_left_click_combo"))
        self.ctrl_left_click_combo.addItem(_fromUtf8(""))
        self.ctrl_left_click_combo.addItem(_fromUtf8(""))
        self.ctrl_left_click_combo.addItem(_fromUtf8(""))
        self.ctrl_left_click_combo.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.ctrl_left_click_combo)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout, 10, 0, 1, 1)
        self.toggle_view_button = QtGui.QPushButton(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggle_view_button.sizePolicy().hasHeightForWidth())
        self.toggle_view_button.setSizePolicy(sizePolicy)
        self.toggle_view_button.setObjectName(_fromUtf8("toggle_view_button"))
        self.gridLayout.addWidget(self.toggle_view_button, 0, 0, 1, 1)
        self.dock_picking.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dock_picking)
        self.action_A1 = QtGui.QAction(MainWindow)
        self.action_A1.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/qrc/074.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_A1.setIcon(icon)
        self.action_A1.setObjectName(_fromUtf8("action_A1"))
        self.action_A2 = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/qrc/002.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_A2.setIcon(icon1)
        self.action_A2.setObjectName(_fromUtf8("action_A2"))
        self.action_A3 = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/qrc/097.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_A3.setIcon(icon2)
        self.action_A3.setObjectName(_fromUtf8("action_A3"))
        self.action_GRP1 = QtGui.QAction(MainWindow)
        self.action_GRP1.setObjectName(_fromUtf8("action_GRP1"))
        self.actionGRP2 = QtGui.QAction(MainWindow)
        self.actionGRP2.setObjectName(_fromUtf8("actionGRP2"))
        self.actionGRP3 = QtGui.QAction(MainWindow)
        self.actionGRP3.setObjectName(_fromUtf8("actionGRP3"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Group.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.tbar_grp.addAction(self.action_GRP1)
        self.tbar_grp.addAction(self.actionGRP2)
        self.tbar_grp.addAction(self.actionGRP3)
        self.tbar_1.addAction(self.action_A1)
        self.tbar_1.addAction(self.action_A2)
        self.tbar_1.addAction(self.action_A3)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menu_Group.setTitle(_translate("MainWindow", "&Group", None))
        self.menu_Tools.setTitle(_translate("MainWindow", "&Tools", None))
        self.menu_View.setTitle(_translate("MainWindow", "&View", None))
        self.dock_msg.setWindowTitle(_translate("MainWindow", "Messages", None))
        self.tbar_grp.setWindowTitle(_translate("MainWindow", "Grouping Toolbar", None))
        self.tbar_grp.setToolTip(_translate("MainWindow", "Group Toolbar", None))
        self.tbar_grp.setStatusTip(_translate("MainWindow", "Group Tools", None))
        self.tbar_1.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.dock_view1.setWindowTitle(_translate("MainWindow", "View 1", None))
        self.btn_switch.setToolTip(_translate("MainWindow", "Switch Background for Printing", None))
        self.btn_switch.setText(_translate("MainWindow", "Switch", None))
        self.btn_bgcolor2.setText(_translate("MainWindow", "BG 2 Color", None))
        self.btn_edgecolor.setText(_translate("MainWindow", "Edge Color", None))
        self.btn_perspectivetoggle.setText(_translate("MainWindow", "Toggle Pers.", None))
        self.btn_bgcolor1.setText(_translate("MainWindow", "BG 1 Color", None))
        self.btn_nofillededge.setText(_translate("MainWindow", "No Filled Edge", None))
        self.btn_elementcolor.setText(_translate("MainWindow", "Element Color", None))
        self.btn_togglewire.setText(_translate("MainWindow", "Toggle Wire", None))
        self.btn_saveimg.setText(_translate("MainWindow", "Save IMG", None))
        self.dock_picking.setWindowTitle(_translate("MainWindow", "Picking", None))
        self.box_pick_button.setText(_translate("MainWindow", "Box Pick", None))
        self.points_button.setText(_translate("MainWindow", "Points", None))
        self.bars_button.setText(_translate("MainWindow", "Bars", None))
        self.single_pick_button.setText(_translate("MainWindow", "Single Pick", None))
        self.toggle_hidden_button.setText(_translate("MainWindow", "Toggle Hidden", None))
        self.remove_selection_button.setText(_translate("MainWindow", "Remove", None))
        self.tris_button.setText(_translate("MainWindow", "Tris", None))
        self.any_button.setText(_translate("MainWindow", "Any", None))
        self.nodes_button.setText(_translate("MainWindow", "Nodes", None))
        self.replace_selection_button.setText(_translate("MainWindow", "Replace", None))
        self.append_selection_button.setText(_translate("MainWindow", "Append", None))
        self.elements_button.setText(_translate("MainWindow", "Elements", None))
        self.poly_pick_button.setText(_translate("MainWindow", "Poly Pick", None))
        self.quads_button.setText(_translate("MainWindow", "Quads", None))
        self.label.setText(_translate("MainWindow", "Left-Click", None))
        self.left_click_combo.setItemText(0, _translate("MainWindow", "Rotate", None))
        self.left_click_combo.setItemText(1, _translate("MainWindow", "Pan", None))
        self.left_click_combo.setItemText(2, _translate("MainWindow", "Zoom", None))
        self.left_click_combo.setItemText(3, _translate("MainWindow", "Select", None))
        self.label_2.setText(_translate("MainWindow", "Middle-Click", None))
        self.middle_click_combo.setItemText(0, _translate("MainWindow", "Rotate", None))
        self.middle_click_combo.setItemText(1, _translate("MainWindow", "Pan", None))
        self.middle_click_combo.setItemText(2, _translate("MainWindow", "Zoom", None))
        self.middle_click_combo.setItemText(3, _translate("MainWindow", "Select", None))
        self.label_3.setText(_translate("MainWindow", "Right-Click", None))
        self.right_click_combo.setItemText(0, _translate("MainWindow", "Rotate", None))
        self.right_click_combo.setItemText(1, _translate("MainWindow", "Pan", None))
        self.right_click_combo.setItemText(2, _translate("MainWindow", "Zoom", None))
        self.right_click_combo.setItemText(3, _translate("MainWindow", "Select", None))
        self.label_4.setText(_translate("MainWindow", "Ctrl-Left-Click", None))
        self.ctrl_left_click_combo.setItemText(0, _translate("MainWindow", "Rotate", None))
        self.ctrl_left_click_combo.setItemText(1, _translate("MainWindow", "Pan", None))
        self.ctrl_left_click_combo.setItemText(2, _translate("MainWindow", "Zoom", None))
        self.ctrl_left_click_combo.setItemText(3, _translate("MainWindow", "Select", None))
        self.toggle_view_button.setText(_translate("MainWindow", "Toggle View", None))
        self.action_A1.setText(_translate("MainWindow", "&A1", None))
        self.action_A2.setText(_translate("MainWindow", "&A2", None))
        self.action_A3.setText(_translate("MainWindow", "&A3", None))
        self.action_GRP1.setText(_translate("MainWindow", "&GRP1", None))
        self.actionGRP2.setText(_translate("MainWindow", "GRP2", None))
        self.actionGRP3.setText(_translate("MainWindow", "GRP3", None))
        self.actionOpen.setText(_translate("MainWindow", "&Open...", None))

import viewqrc_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

