# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created: Tue Dec 30 10:59:37 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1155, 831)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.frame_3 = QtGui.QFrame(self.splitter_2)
        self.frame_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtGui.QGridLayout(self.frame_3)
        self.gridLayout.setContentsMargins(0, 9, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_bgcolor1 = QtGui.QPushButton(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_bgcolor1.sizePolicy().hasHeightForWidth())
        self.btn_bgcolor1.setSizePolicy(sizePolicy)
        self.btn_bgcolor1.setObjectName("btn_bgcolor1")
        self.gridLayout.addWidget(self.btn_bgcolor1, 0, 0, 1, 1)
        self.btn_bgcolor2 = QtGui.QPushButton(self.frame_3)
        self.btn_bgcolor2.setObjectName("btn_bgcolor2")
        self.gridLayout.addWidget(self.btn_bgcolor2, 1, 0, 1, 1)
        self.btn_edgecolor = QtGui.QPushButton(self.frame_3)
        self.btn_edgecolor.setObjectName("btn_edgecolor")
        self.gridLayout.addWidget(self.btn_edgecolor, 2, 0, 1, 1)
        self.btn_elementcolor = QtGui.QPushButton(self.frame_3)
        self.btn_elementcolor.setObjectName("btn_elementcolor")
        self.gridLayout.addWidget(self.btn_elementcolor, 3, 0, 1, 1)
        self.btn_nofillededge = QtGui.QPushButton(self.frame_3)
        self.btn_nofillededge.setObjectName("btn_nofillededge")
        self.gridLayout.addWidget(self.btn_nofillededge, 4, 0, 1, 1)
        self.btn_switch = QtGui.QPushButton(self.frame_3)
        self.btn_switch.setObjectName("btn_switch")
        self.gridLayout.addWidget(self.btn_switch, 5, 0, 1, 1)
        self.btn_perspectivetoggle = QtGui.QPushButton(self.frame_3)
        self.btn_perspectivetoggle.setObjectName("btn_perspectivetoggle")
        self.gridLayout.addWidget(self.btn_perspectivetoggle, 6, 0, 1, 1)
        self.btn_togglewire = QtGui.QPushButton(self.frame_3)
        self.btn_togglewire.setObjectName("btn_togglewire")
        self.gridLayout.addWidget(self.btn_togglewire, 7, 0, 1, 1)
        self.btn_saveimg = QtGui.QPushButton(self.frame_3)
        self.btn_saveimg.setObjectName("btn_saveimg")
        self.gridLayout.addWidget(self.btn_saveimg, 8, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtGui.QFrame(self.splitter)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.vl = QtGui.QVBoxLayout()
        self.vl.setObjectName("vl")
        self.gridLayout_2.addLayout(self.vl, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.splitter)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.toggle_view_button = QtGui.QPushButton(self.frame_2)
        self.toggle_view_button.setGeometry(QtCore.QRect(90, 10, 101, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggle_view_button.sizePolicy().hasHeightForWidth())
        self.toggle_view_button.setSizePolicy(sizePolicy)
        self.toggle_view_button.setObjectName("toggle_view_button")
        self.single_pick_button = QtGui.QPushButton(self.frame_2)
        self.single_pick_button.setGeometry(QtCore.QRect(40, 65, 75, 23))
        self.single_pick_button.setAutoDefault(True)
        self.single_pick_button.setObjectName("single_pick_button")
        self.box_pick_button = QtGui.QPushButton(self.frame_2)
        self.box_pick_button.setGeometry(QtCore.QRect(40, 86, 75, 23))
        self.box_pick_button.setAutoDefault(True)
        self.box_pick_button.setObjectName("box_pick_button")
        self.poly_pick_button = QtGui.QPushButton(self.frame_2)
        self.poly_pick_button.setGeometry(QtCore.QRect(40, 107, 75, 23))
        self.poly_pick_button.setAutoDefault(True)
        self.poly_pick_button.setDefault(False)
        self.poly_pick_button.setFlat(False)
        self.poly_pick_button.setObjectName("poly_pick_button")
        self.any_button = QtGui.QPushButton(self.frame_2)
        self.any_button.setGeometry(QtCore.QRect(160, 64, 75, 23))
        self.any_button.setAutoDefault(True)
        self.any_button.setObjectName("any_button")
        self.elements_button = QtGui.QPushButton(self.frame_2)
        self.elements_button.setGeometry(QtCore.QRect(160, 106, 75, 23))
        self.elements_button.setAutoDefault(True)
        self.elements_button.setDefault(False)
        self.elements_button.setFlat(False)
        self.elements_button.setObjectName("elements_button")
        self.nodes_button = QtGui.QPushButton(self.frame_2)
        self.nodes_button.setGeometry(QtCore.QRect(160, 85, 75, 23))
        self.nodes_button.setAutoDefault(True)
        self.nodes_button.setObjectName("nodes_button")
        self.points_button = QtGui.QPushButton(self.frame_2)
        self.points_button.setGeometry(QtCore.QRect(160, 127, 75, 23))
        self.points_button.setAutoDefault(True)
        self.points_button.setDefault(False)
        self.points_button.setFlat(False)
        self.points_button.setObjectName("points_button")
        self.bars_button = QtGui.QPushButton(self.frame_2)
        self.bars_button.setGeometry(QtCore.QRect(160, 148, 75, 23))
        self.bars_button.setAutoDefault(True)
        self.bars_button.setDefault(False)
        self.bars_button.setFlat(False)
        self.bars_button.setObjectName("bars_button")
        self.tris_button = QtGui.QPushButton(self.frame_2)
        self.tris_button.setGeometry(QtCore.QRect(160, 169, 75, 23))
        self.tris_button.setAutoDefault(True)
        self.tris_button.setDefault(False)
        self.tris_button.setFlat(False)
        self.tris_button.setObjectName("tris_button")
        self.quads_button = QtGui.QPushButton(self.frame_2)
        self.quads_button.setGeometry(QtCore.QRect(160, 190, 75, 23))
        self.quads_button.setAutoDefault(True)
        self.quads_button.setDefault(False)
        self.quads_button.setFlat(False)
        self.quads_button.setObjectName("quads_button")
        self.selection_box = QtGui.QLineEdit(self.frame_2)
        self.selection_box.setGeometry(QtCore.QRect(10, 240, 281, 20))
        self.selection_box.setObjectName("selection_box")
        self.toggle_hidden_button = QtGui.QPushButton(self.frame_2)
        self.toggle_hidden_button.setGeometry(QtCore.QRect(90, 270, 101, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggle_hidden_button.sizePolicy().hasHeightForWidth())
        self.toggle_hidden_button.setSizePolicy(sizePolicy)
        self.toggle_hidden_button.setObjectName("toggle_hidden_button")
        self.gridLayout_4.addWidget(self.splitter_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1155, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txt_msg = QtGui.QPlainTextEdit(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_msg.sizePolicy().hasHeightForWidth())
        self.txt_msg.setSizePolicy(sizePolicy)
        self.txt_msg.setMinimumSize(QtCore.QSize(0, 120))
        self.txt_msg.setMaximumSize(QtCore.QSize(16777215, 120))
        self.txt_msg.setObjectName("txt_msg")
        self.gridLayout_3.addWidget(self.txt_msg, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_bgcolor1.setText(QtGui.QApplication.translate("MainWindow", "BG 1 Color", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_bgcolor2.setText(QtGui.QApplication.translate("MainWindow", "BG 2 Color", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_edgecolor.setText(QtGui.QApplication.translate("MainWindow", "Edge Color", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_elementcolor.setText(QtGui.QApplication.translate("MainWindow", "Element Color", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_nofillededge.setText(QtGui.QApplication.translate("MainWindow", "No Filled Edge", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_switch.setToolTip(QtGui.QApplication.translate("MainWindow", "Switch Background for Printing", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_switch.setText(QtGui.QApplication.translate("MainWindow", "Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_perspectivetoggle.setText(QtGui.QApplication.translate("MainWindow", "Toggle Pers.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_togglewire.setText(QtGui.QApplication.translate("MainWindow", "Toggle Wire", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_saveimg.setText(QtGui.QApplication.translate("MainWindow", "Save IMG", None, QtGui.QApplication.UnicodeUTF8))
        self.toggle_view_button.setText(QtGui.QApplication.translate("MainWindow", "Toggle View", None, QtGui.QApplication.UnicodeUTF8))
        self.single_pick_button.setText(QtGui.QApplication.translate("MainWindow", "Single Pick", None, QtGui.QApplication.UnicodeUTF8))
        self.box_pick_button.setText(QtGui.QApplication.translate("MainWindow", "Box Pick", None, QtGui.QApplication.UnicodeUTF8))
        self.poly_pick_button.setText(QtGui.QApplication.translate("MainWindow", "Poly Pick", None, QtGui.QApplication.UnicodeUTF8))
        self.any_button.setText(QtGui.QApplication.translate("MainWindow", "Any", None, QtGui.QApplication.UnicodeUTF8))
        self.elements_button.setText(QtGui.QApplication.translate("MainWindow", "Elements", None, QtGui.QApplication.UnicodeUTF8))
        self.nodes_button.setText(QtGui.QApplication.translate("MainWindow", "Nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.points_button.setText(QtGui.QApplication.translate("MainWindow", "Points", None, QtGui.QApplication.UnicodeUTF8))
        self.bars_button.setText(QtGui.QApplication.translate("MainWindow", "Bars", None, QtGui.QApplication.UnicodeUTF8))
        self.tris_button.setText(QtGui.QApplication.translate("MainWindow", "Tris", None, QtGui.QApplication.UnicodeUTF8))
        self.quads_button.setText(QtGui.QApplication.translate("MainWindow", "Quads", None, QtGui.QApplication.UnicodeUTF8))
        self.toggle_hidden_button.setText(QtGui.QApplication.translate("MainWindow", "Toggle Hidden", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open...", None, QtGui.QApplication.UnicodeUTF8))

