# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\CODE\10_PROJECT\FEMAnalysisTool\fem_post\view\docks\dockui_picking.ui'
#
# Created: Mon Mar 23 05:36:08 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dock_Picking(object):
    def setupUi(self, Dock_Picking):
        Dock_Picking.setObjectName(_fromUtf8("Dock_Picking"))
        Dock_Picking.resize(188, 493)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dock_Picking.sizePolicy().hasHeightForWidth())
        Dock_Picking.setSizePolicy(sizePolicy)
        Dock_Picking.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btn_box_pick = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_box_pick.sizePolicy().hasHeightForWidth())
        self.btn_box_pick.setSizePolicy(sizePolicy)
        self.btn_box_pick.setAutoDefault(True)
        self.btn_box_pick.setObjectName(_fromUtf8("btn_box_pick"))
        self.gridLayout.addWidget(self.btn_box_pick, 5, 2, 1, 1)
        self.btn_any = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_any.sizePolicy().hasHeightForWidth())
        self.btn_any.setSizePolicy(sizePolicy)
        self.btn_any.setAutoDefault(True)
        self.btn_any.setObjectName(_fromUtf8("btn_any"))
        self.gridLayout.addWidget(self.btn_any, 4, 3, 1, 1)
        self.btn_single_pick = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_single_pick.sizePolicy().hasHeightForWidth())
        self.btn_single_pick.setSizePolicy(sizePolicy)
        self.btn_single_pick.setAutoDefault(True)
        self.btn_single_pick.setObjectName(_fromUtf8("btn_single_pick"))
        self.gridLayout.addWidget(self.btn_single_pick, 4, 2, 1, 1)
        self.btn_nodes = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_nodes.sizePolicy().hasHeightForWidth())
        self.btn_nodes.setSizePolicy(sizePolicy)
        self.btn_nodes.setAutoDefault(True)
        self.btn_nodes.setObjectName(_fromUtf8("btn_nodes"))
        self.gridLayout.addWidget(self.btn_nodes, 5, 3, 1, 1)
        self.btn_replace_selection = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_replace_selection.sizePolicy().hasHeightForWidth())
        self.btn_replace_selection.setSizePolicy(sizePolicy)
        self.btn_replace_selection.setAutoDefault(True)
        self.btn_replace_selection.setObjectName(_fromUtf8("btn_replace_selection"))
        self.gridLayout.addWidget(self.btn_replace_selection, 8, 2, 1, 1)
        self.btn_poly_pick = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_poly_pick.sizePolicy().hasHeightForWidth())
        self.btn_poly_pick.setSizePolicy(sizePolicy)
        self.btn_poly_pick.setAutoDefault(True)
        self.btn_poly_pick.setDefault(False)
        self.btn_poly_pick.setFlat(False)
        self.btn_poly_pick.setObjectName(_fromUtf8("btn_poly_pick"))
        self.gridLayout.addWidget(self.btn_poly_pick, 6, 2, 1, 1)
        self.btn_quads = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_quads.sizePolicy().hasHeightForWidth())
        self.btn_quads.setSizePolicy(sizePolicy)
        self.btn_quads.setAutoDefault(True)
        self.btn_quads.setDefault(False)
        self.btn_quads.setFlat(False)
        self.btn_quads.setObjectName(_fromUtf8("btn_quads"))
        self.gridLayout.addWidget(self.btn_quads, 10, 3, 1, 1)
        self.btn_tris = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_tris.sizePolicy().hasHeightForWidth())
        self.btn_tris.setSizePolicy(sizePolicy)
        self.btn_tris.setAutoDefault(True)
        self.btn_tris.setDefault(False)
        self.btn_tris.setFlat(False)
        self.btn_tris.setObjectName(_fromUtf8("btn_tris"))
        self.gridLayout.addWidget(self.btn_tris, 9, 3, 1, 1)
        self.btn_elements = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_elements.sizePolicy().hasHeightForWidth())
        self.btn_elements.setSizePolicy(sizePolicy)
        self.btn_elements.setAutoDefault(True)
        self.btn_elements.setDefault(False)
        self.btn_elements.setFlat(False)
        self.btn_elements.setObjectName(_fromUtf8("btn_elements"))
        self.gridLayout.addWidget(self.btn_elements, 6, 3, 1, 1)
        self.btn_bars = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_bars.sizePolicy().hasHeightForWidth())
        self.btn_bars.setSizePolicy(sizePolicy)
        self.btn_bars.setAutoDefault(True)
        self.btn_bars.setDefault(False)
        self.btn_bars.setFlat(False)
        self.btn_bars.setObjectName(_fromUtf8("btn_bars"))
        self.gridLayout.addWidget(self.btn_bars, 8, 3, 1, 1)
        self.btn_remove_selection = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_remove_selection.sizePolicy().hasHeightForWidth())
        self.btn_remove_selection.setSizePolicy(sizePolicy)
        self.btn_remove_selection.setAutoDefault(True)
        self.btn_remove_selection.setDefault(False)
        self.btn_remove_selection.setFlat(False)
        self.btn_remove_selection.setObjectName(_fromUtf8("btn_remove_selection"))
        self.gridLayout.addWidget(self.btn_remove_selection, 10, 2, 1, 1)
        self.btn_points = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_points.sizePolicy().hasHeightForWidth())
        self.btn_points.setSizePolicy(sizePolicy)
        self.btn_points.setAutoDefault(True)
        self.btn_points.setDefault(False)
        self.btn_points.setFlat(False)
        self.btn_points.setObjectName(_fromUtf8("btn_points"))
        self.gridLayout.addWidget(self.btn_points, 7, 3, 1, 1)
        self.btn_append_selection = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_append_selection.sizePolicy().hasHeightForWidth())
        self.btn_append_selection.setSizePolicy(sizePolicy)
        self.btn_append_selection.setAutoDefault(True)
        self.btn_append_selection.setObjectName(_fromUtf8("btn_append_selection"))
        self.gridLayout.addWidget(self.btn_append_selection, 9, 2, 1, 1)
        self.cbx_left_click = QtGui.QComboBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbx_left_click.sizePolicy().hasHeightForWidth())
        self.cbx_left_click.setSizePolicy(sizePolicy)
        self.cbx_left_click.setMinimumSize(QtCore.QSize(0, 0))
        self.cbx_left_click.setObjectName(_fromUtf8("cbx_left_click"))
        self.cbx_left_click.addItem(_fromUtf8(""))
        self.cbx_left_click.addItem(_fromUtf8(""))
        self.cbx_left_click.addItem(_fromUtf8(""))
        self.cbx_left_click.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbx_left_click, 14, 3, 1, 1)
        self.cbx_right_click = QtGui.QComboBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbx_right_click.sizePolicy().hasHeightForWidth())
        self.cbx_right_click.setSizePolicy(sizePolicy)
        self.cbx_right_click.setMinimumSize(QtCore.QSize(0, 0))
        self.cbx_right_click.setObjectName(_fromUtf8("cbx_right_click"))
        self.cbx_right_click.addItem(_fromUtf8(""))
        self.cbx_right_click.addItem(_fromUtf8(""))
        self.cbx_right_click.addItem(_fromUtf8(""))
        self.cbx_right_click.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbx_right_click, 16, 3, 1, 1)
        self.cbx_ctrl_left_click = QtGui.QComboBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbx_ctrl_left_click.sizePolicy().hasHeightForWidth())
        self.cbx_ctrl_left_click.setSizePolicy(sizePolicy)
        self.cbx_ctrl_left_click.setMinimumSize(QtCore.QSize(0, 0))
        self.cbx_ctrl_left_click.setObjectName(_fromUtf8("cbx_ctrl_left_click"))
        self.cbx_ctrl_left_click.addItem(_fromUtf8(""))
        self.cbx_ctrl_left_click.addItem(_fromUtf8(""))
        self.cbx_ctrl_left_click.addItem(_fromUtf8(""))
        self.cbx_ctrl_left_click.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbx_ctrl_left_click, 17, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 17, 2, 1, 1)
        self.cbx_middle_click = QtGui.QComboBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbx_middle_click.sizePolicy().hasHeightForWidth())
        self.cbx_middle_click.setSizePolicy(sizePolicy)
        self.cbx_middle_click.setMinimumSize(QtCore.QSize(0, 0))
        self.cbx_middle_click.setObjectName(_fromUtf8("cbx_middle_click"))
        self.cbx_middle_click.addItem(_fromUtf8(""))
        self.cbx_middle_click.addItem(_fromUtf8(""))
        self.cbx_middle_click.addItem(_fromUtf8(""))
        self.cbx_middle_click.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbx_middle_click, 15, 3, 1, 1)
        self.label = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 14, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 16, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 15, 2, 1, 1)
        self.btn_toggle_hidden = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle_hidden.sizePolicy().hasHeightForWidth())
        self.btn_toggle_hidden.setSizePolicy(sizePolicy)
        self.btn_toggle_hidden.setObjectName(_fromUtf8("btn_toggle_hidden"))
        self.gridLayout.addWidget(self.btn_toggle_hidden, 2, 3, 1, 1)
        self.btn_toggle_view = QtGui.QPushButton(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle_view.sizePolicy().hasHeightForWidth())
        self.btn_toggle_view.setSizePolicy(sizePolicy)
        self.btn_toggle_view.setObjectName(_fromUtf8("btn_toggle_view"))
        self.gridLayout.addWidget(self.btn_toggle_view, 2, 2, 1, 1)
        self.lnedt_selection = QtGui.QLineEdit(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnedt_selection.sizePolicy().hasHeightForWidth())
        self.lnedt_selection.setSizePolicy(sizePolicy)
        self.lnedt_selection.setObjectName(_fromUtf8("lnedt_selection"))
        self.gridLayout.addWidget(self.lnedt_selection, 12, 2, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 18, 2, 1, 2)
        Dock_Picking.setWidget(self.dockWidgetContents)

        self.retranslateUi(Dock_Picking)
        QtCore.QMetaObject.connectSlotsByName(Dock_Picking)

    def retranslateUi(self, Dock_Picking):
        Dock_Picking.setToolTip(_translate("Dock_Picking", "Picking Dock", None))
        Dock_Picking.setStatusTip(_translate("Dock_Picking", "Picking Utility Dock", None))
        Dock_Picking.setWindowTitle(_translate("Dock_Picking", "Picking", None))
        self.btn_box_pick.setText(_translate("Dock_Picking", "Box Pick", None))
        self.btn_any.setText(_translate("Dock_Picking", "Any", None))
        self.btn_single_pick.setText(_translate("Dock_Picking", "Single Pick", None))
        self.btn_nodes.setText(_translate("Dock_Picking", "Nodes", None))
        self.btn_replace_selection.setText(_translate("Dock_Picking", "Replace", None))
        self.btn_poly_pick.setText(_translate("Dock_Picking", "Poly Pick", None))
        self.btn_quads.setText(_translate("Dock_Picking", "Quads", None))
        self.btn_tris.setText(_translate("Dock_Picking", "Tris", None))
        self.btn_elements.setText(_translate("Dock_Picking", "Elements", None))
        self.btn_bars.setText(_translate("Dock_Picking", "Bars", None))
        self.btn_remove_selection.setText(_translate("Dock_Picking", "Remove", None))
        self.btn_points.setText(_translate("Dock_Picking", "Points", None))
        self.btn_append_selection.setText(_translate("Dock_Picking", "Append", None))
        self.cbx_left_click.setItemText(0, _translate("Dock_Picking", "Rotate", None))
        self.cbx_left_click.setItemText(1, _translate("Dock_Picking", "Pan", None))
        self.cbx_left_click.setItemText(2, _translate("Dock_Picking", "Zoom", None))
        self.cbx_left_click.setItemText(3, _translate("Dock_Picking", "Select", None))
        self.cbx_right_click.setItemText(0, _translate("Dock_Picking", "Rotate", None))
        self.cbx_right_click.setItemText(1, _translate("Dock_Picking", "Pan", None))
        self.cbx_right_click.setItemText(2, _translate("Dock_Picking", "Zoom", None))
        self.cbx_right_click.setItemText(3, _translate("Dock_Picking", "Select", None))
        self.cbx_ctrl_left_click.setItemText(0, _translate("Dock_Picking", "Rotate", None))
        self.cbx_ctrl_left_click.setItemText(1, _translate("Dock_Picking", "Pan", None))
        self.cbx_ctrl_left_click.setItemText(2, _translate("Dock_Picking", "Zoom", None))
        self.cbx_ctrl_left_click.setItemText(3, _translate("Dock_Picking", "Select", None))
        self.label_4.setText(_translate("Dock_Picking", "Ctrl-Left-Click", None))
        self.cbx_middle_click.setItemText(0, _translate("Dock_Picking", "Rotate", None))
        self.cbx_middle_click.setItemText(1, _translate("Dock_Picking", "Pan", None))
        self.cbx_middle_click.setItemText(2, _translate("Dock_Picking", "Zoom", None))
        self.cbx_middle_click.setItemText(3, _translate("Dock_Picking", "Select", None))
        self.label.setText(_translate("Dock_Picking", "Left-Click", None))
        self.label_3.setText(_translate("Dock_Picking", "Right-Click", None))
        self.label_2.setText(_translate("Dock_Picking", "Middle-Click", None))
        self.btn_toggle_hidden.setText(_translate("Dock_Picking", "Toggle Hidden", None))
        self.btn_toggle_view.setText(_translate("Dock_Picking", "Toggle View", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dock_Picking = QtGui.QDockWidget()
    ui = Ui_Dock_Picking()
    ui.setupUi(Dock_Picking)
    Dock_Picking.show()
    sys.exit(app.exec_())

